### ISSUE TITLE
Shena Laptop Tracking Info

### ISSUE THREAD

**Issue by andyl** [bugmark/outreachy#1]
Shena has been trying to get in touch with Susy and Elizabeth at Mozilla, regarding the laptop tracking information, as I need to coordinate the delivery at the address.  Please post the tracking info here.

**Comment by andyl** [comment]
Per Susy: "Not yet available. Problems in customs. I'll pass on updates as soon as I have them."

**Comment by andyl** [comment]
Update per Suzy: laptop passing thru canadian customs...

**Comment by snehasi** [comment]
Andy and Susy - thank you!
