### ISSUE TITLE
Polish bugmark.net website

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/outreachy#10]
- [x] target towards corporate sponsored open source
- [x] explain the three hypotheses that we have
  - Bugmark reduces feature costs
  - Bugmark reduces time to fix issues
  - Bugmark reduces recruitment cost
- [x] add color
- [ ] maybe add images

**Comment by andyl** [comment]
Now that I fixed the SSL issue, I'm going to take a crack at revising the site content over the coming days.  My focus will be almost entirely on copywriting.  Watch this space!

**Comment by snehasi** [comment]
Would it be alright if I went ahead with the hypotheses that Georg has outlined? Maybe @andyl could revise that content once I'm done?

**Comment by andyl** [comment]
@snehasi Yes by all means!!  Plz push your work into a separate branch, then let us have a look before submitting a PR.

**Comment by snehasi** [comment]
Great, thank you!

**Comment by andyl** [comment]
@snehasi  - next week for the first time we'll begin to discuss Bugmark customers, product/market fit, etc.  FYI [this book](https://www.amazon.com/Entrepreneurs-Guide-Customer-Development-Epiphany/dp/0982743602/ref=sr_1_fkmr2_1?ie=UTF8&qid=1529220855&sr=8-1-fkmr2&keywords=entrepeneur%27s+guide+to+customer+development) outlines the framework that I like to use for customer development.  If you are interested in startup marketing this is a good reference.

**Comment by snehasi** [comment]
https://github.com/bugmark/website/pull/17
