### ISSUE TITLE
Test the intern app locally

### ISSUE THREAD

**Issue by snehasi** [bugmark/outreachy#11]
- Test the minimal intern app on local machine

- Report and fix bugs

- Make changes in the UI

**Comment by andyl** [comment]
This is great.  Sneha I've updated the README for the Intern exercise with some build instructions.  

Plz send me a calendar invite if you'd like to pair-program to get your environment set up.  

If you'd like me to make a clone of the Intern host, let me know.

**Comment by snehasi** [comment]
Hi @andyl , 
Thanks so much. I have a question:
Which file is the Partcipants.yml in https://github.com/bugmark-trial/intern1/blob/master/.trial_data/Participants.yml referring to? I'm getting an error while trying to do system_build which I think is related to this.
Thanks!

**Comment by snehasi** [comment]
Thanks @andyl for giving me the yml files! 
Here's my report of a bug: https://github.com/bugmark/test_bench/issues/98 , and the related PR: https://github.com/bugmark/test_bench/pull/111
