### ISSUE TITLE
Analysing user data from bmx bot

### ISSUE THREAD

**Issue by snehasi** [bugmark/outreachy#12]
Hi @andyl , @GeorgLink 

I saw that the balance data for users, is only increasing at the end of the 15 day simulation period. How is this possible with no external investments in the simulation platform?
Imho, although balance should be cumulative (i.e. previous day's balance has been accounted for), it should also decrease for at least some users, at the end of the simulation.
I have visualised data for some users to see the trend pattern, here.:

![screen shot 2018-06-19 at 6 04 22 pm](https://user-images.githubusercontent.com/22666460/41600109-a3654c64-73f2-11e8-9350-82b9bfcf42f6.png)

The same is the case with earnings, for all users in the simulation period :
![screen shot 2018-06-19 at 6 22 05 pm](https://user-images.githubusercontent.com/22666460/41600240-f9f806de-73f2-11e8-8e58-ebc6ddb6218d.png)
I guess the earnings graph would only make sense if it was cumulative instead of on a per day basis, if I am not wrong.

Also, what exactly is the contract_payout_frequency in the health data? 

Thanks!

**Comment by GeorgLink** [comment]
Hi @snehasi 

What bot are you analyzing?
If it is my bot, then you are correct, that the total sum of budgets will not change. The simulation has very wealthy funders who pay the workers. Thus, all workers earn good money and their balances will continuously go up. It is the balance of funders that go down during the simulation.

You can find the calculation for the contract_payout_frequency in the `run.rb` file. It is the percentage of contracts that a user had and got paid out.

**Comment by snehasi** [comment]
Hi @GeorgLink

Yes, this is for the bmx bot. 
Thanks for clarifying!
