### ISSUE TITLE
Grafana dashboard panels for user statistics

### ISSUE THREAD

**Issue by snehasi** [bugmark/outreachy#15]
https://github.com/bugmark/test_bench/issues/120

**Comment by andyl** [comment]
Here's some syntax for the script:
- User Balance: `user.balance`
- User Reserve: `user.token_reserve`
- User Available: `user.token_available` (balance == token_reserve + token_available)
- User open offers: `user.offers.open.count`
- User closed offers: `user.offers.not_open.count` (valid states: open, closed, suspended, cancelled, crossed)
- User contracts: `user.contracts.count` (open/closed modifiers probably work here)

**Comment by snehasi** [comment]
https://github.com/bugmark/test_bench/pull/128

**Comment by snehasi** [comment]
Done.
