### ISSUE TITLE
Understand how the bot scripts work

### ISSUE THREAD

**Issue by snehasi** [bugmark/outreachy#2]
This involves the following tasks:

- [x] List the bot scripts, and briefly describe them in the issue comments.

- [ ] Stretch goal : Write your own bot script for generating new data, if needed.

**Comment by snehasi** [comment]
- [x] `exchange/script/bot/buy`

- [x] `exchange/script/bot/fast_buy`

- [x] `bmx-bot/sbot/run.rb`

**Comment by snehasi** [comment]
Essentially, the `buy` bot has buy and cross functions. `cross` works on the Offer class defined in `exchange/app/models/offer.rb`, takes the `.open` function from that file, it gets all objects where Offer status is open. Contracts are created, on each such offer. For the first half, bot script runs with make offers faster than the later half of the iteration.  Then it creates buy offers, calls cross function which creates contracts for alternate buy offers. `fast_buy` bot is almost the same except that it doesn't go to sleep, so the simulation is faster.
`bmx_run` bot takes the `settings.yaml` to see which env it has to simulate, prints out the metrics in csv files for different kinds of `workers` and `funders`.

**Comment by GeorgLink** [comment]
sounds about right :-) 

Well done!
