### ISSUE TITLE
Run bot scripts on the local install of Bugmark exchange

### ISSUE THREAD

**Issue by snehasi** [bugmark/outreachy#3]

**Comment by snehasi** [comment]
[`outreachy/graphs/fast_buy_chart.html`](https://github.com/bugmark/outreachy/blob/master/graphs/fast_buy_chart.html) consists of a working visualisation using `chart.js` and `lodash.js` on:

-  open offers
-  contracts
-  escrows
combined for each cycle in the bot simulation.

 The graph can be seen here : [`outreachy/graphs/fast_buy.png`](https://github.com/bugmark/outreachy/blob/master/graphs/fast_buy.png)

**Comment by snehasi** [comment]
I've updated the [`outreachy/graphs/fast_buy_chart_v2.html`](https://github.com/bugmark/outreachy/blob/master/graphs/fast_buy_chart_v2.html) using `chart.js` and `jquery`. Also, removed the API call, for fast loading.

**Comment by GeorgLink** [comment]
​Do you have a server or place where we can see the page in action?

**Comment by snehasi** [comment]
We can get a domain for the website gallery on visualisation, for the time being - I've set it up [here](http://52.66.30.67:1234/fast_buy_chart_v2.html).

**Comment by GeorgLink** [comment]
​Thank you, that is exactly what I was looking for.

**Comment by snehasi** [comment]
Hey @andyl , @GeorgLink 

The issues for the first milestone were complete. Should I close them, if no changes are needed?

Thanks!

**Comment by GeorgLink** [comment]
Yes, we can close it. I'll do it right away.
