### ISSUE TITLE
Parse the CSV data files generated in bot simulations

### ISSUE THREAD

**Issue by snehasi** [bugmark/outreachy#4]

**Comment by snehasi** [comment]
94bbd431cca6361f4435478998c6a449a648ddb1

**Comment by GeorgLink** [comment]
FYI: I changed the format of the CSV file that my simulation generates. 
GeorgLink/bmx-bot#18

Let me know if you want to chat about CSV generation and what data to include and analyze. I am open to ideas and suggestions.

**Comment by snehasi** [comment]
Hi Georg,

I think your current csv format for `bmx-bot/sbot/run.rb` work fine for me. 
I will let you know if I need to change it.

Thanks

**Comment by GeorgLink** [comment]
thank you :-)
