### ISSUE TITLE
Targeted views at present

### ISSUE THREAD

**Issue by snehasi** [bugmark/outreachy#5]
- [x]  Market 

- [x]  Project 

- [x]  Issue 

- [x]  User

**Comment by snehasi** [comment]
For the Bmx bot each funder has his/her own project, and vice versa.

**Comment by GeorgLink** [comment]
> For the Bmx bot each funder has his/her own project, and vice versa. 
Correct

**Comment by GeorgLink** [comment]
As you check off the items, can you please make sure you add where to find these? This can ideally be pull requests.

**Comment by snehasi** [comment]
As I've already committed in the master for some views, I'll just add the links here and proceed to make PRs for any views I add in the future.

1. Issue view : 

- https://github.com/bugmark/outreachy/blob/master/graphs/png/bmxbot_issues_noncumulative.png

- https://github.com/bugmark/outreachy/blob/master/graphs/png/bmxbot_issuesprogress_final.png

- https://github.com/bugmark/outreachy/blob/master/graphs/png/bmxbot_issuesprogressv1.png

2. Market view:

- https://github.com/bugmark/outreachy/blob/master/graphs/png/fastbuybot_line.png

- https://github.com/bugmark/outreachy/blob/master/graphs/png/fast_buy.png

3. User view:

- https://github.com/bugmark/outreachy/blob/master/graphs/png/balance_line_workers.png

- https://github.com/bugmark/outreachy/blob/master/graphs/png/balance_line_funders.png

- https://github.com/bugmark/outreachy/blob/master/graphs/png/balance_line_all_users.png

- https://github.com/bugmark/outreachy/blob/master/graphs/png/balance_bar_all_users.png

- https://github.com/bugmark/outreachy/blob/master/graphs/png/balance_selected_line_smoothing.png

- https://github.com/bugmark/outreachy/blob/master/graphs/png/earnings_all_line.png

- https://github.com/bugmark/outreachy/blob/master/graphs/png/payout_freq.png

**Comment by GeorgLink** [comment]
Thanks Sneha, where is the source code?

Can you send me a pull request to the georglink/bmx-bot so that I can generate the graphs for new runs?

**Comment by snehasi** [comment]
Hi Georg,

The PR: https://github.com/GeorgLink/bmx-bot/pull/23
The source code is present in this repo in the graphs folder, you can just run the js scripts for generating dynamic graphs.

**Comment by GeorgLink** [comment]
Thank you, I'll have a look.
