### ISSUE TITLE
Paper design and overview 

### ISSUE THREAD

**Issue by snehasi** [bugmark/outreachy#8]
The doc link will be posted in the issue comments.

**Comment by GeorgLink** [comment]
Suggestion: create a google doc for us to comment and write on.

**Comment by snehasi** [comment]
The slide deck: https://docs.google.com/presentation/d/1enEKcRlSOJi0uMgmO4jSsTvugjJIoUo1E7RWbzzrVhs/edit?usp=sharing

The doc:
https://docs.google.com/document/d/1C-F8gxS9gSjg6x1_byTuNV2vOn1T5XdV2yGo3Y2COHE/edit?usp=sharing
